-- 코드를 입력하세요
SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM((b.PRICE * s.SALES)) as TOTAL_SALES
FROM 
    BOOK b
LEFT JOIN
    AUTHOR a
ON 
    a.AUTHOR_ID = b.AUTHOR_ID	
LEFT JOIN
    BOOK_SALES  s
ON 
    s.BOOK_ID = b.BOOK_ID	
WHERE 
    YEAR(s.SALES_DATE) = 2022 AND MONTH(s.SALES_DATE) = 1
GROUP BY
    a.AUTHOR_NAME,a.AUTHOR_ID,b.CATEGORY
ORDER BY
    a.AUTHOR_ID ASC, CATEGORY DESC