SELECT 
  ED.ID, 
  CN.COLONY_NAME 
FROM 
  ECOLI_DATA ED 
  INNER JOIN (
    SELECT 
      ID, 
      CASE WHEN SIZE_GROUP = 1 THEN 'CRITICAL' WHEN SIZE_GROUP = 2 THEN 'HIGH' WHEN SIZE_GROUP = 3 THEN 'MEDIUM' WHEN SIZE_GROUP = 4 THEN 'LOW' END AS COLONY_NAME 
    FROM 
      (
        SELECT 
          ID, 
          NTILE(4) OVER (
            ORDER BY 
              SIZE_OF_COLONY DESC
          ) AS SIZE_GROUP 
        FROM 
          ECOLI_DATA
      ) AS NTILE_ECOLI_DATA
  ) AS CN ON ED.ID = CN.ID 
ORDER BY 
  ED.ID;
